### ISSUE TITLE
No KVOListener callback on fast value update of Object field

### ISSUE THREAD

**Issue by rohit-squad** [ahmed-basyouni/AndroidKVO#1]
Whenever we fast update the Object field which is being observed, the registered KVOListener's onValueChange is not getting called. And afterword other KVOListener also stop working.

**Comment by ahmed-basyouni** [comment]
Thank you for the issue.
As for the first part of the issue if you mean by fast update something like that parson.name = "Blah"
The lib doesn't support that yet it only support update using setter and getter
as for And afterword other KVOListener also stop working. I didn't quite follow that
Could you elaborate more ?
